// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckLocalFiles() {
  return window['go']['main']['App']['CheckLocalFiles']();
}

export function GetCharacterData(arg1) {
  return window['go']['main']['App']['GetCharacterData'](arg1);
}

export function GetWeaponData(arg1) {
  return window['go']['main']['App']['GetWeaponData'](arg1);
}

export function LoadGachaTokens() {
  return window['go']['main']['App']['LoadGachaTokens']();
}

export function LoadLocalGachaHistory(arg1) {
  return window['go']['main']['App']['LoadLocalGachaHistory'](arg1);
}

export function OpenDataFolder() {
  return window['go']['main']['App']['OpenDataFolder']();
}

export function ReloadFrontend() {
  return window['go']['main']['App']['ReloadFrontend']();
}

export function WindowClose() {
  return window['go']['main']['App']['WindowClose']();
}

export function WindowMinSize() {
  return window['go']['main']['App']['WindowMinSize']();
}

export function WindowToggleMaxSize() {
  return window['go']['main']['App']['WindowToggleMaxSize']();
}
