// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function RefreshCharGachaHistory() {
  return window['go']['main']['App']['RefreshCharGachaHistory']();
}

export function RefreshWeaponGachaHistory() {
  return window['go']['main']['App']['RefreshWeaponGachaHistory']();
}

export function ReloadFrontend() {
  return window['go']['main']['App']['ReloadFrontend']();
}

export function WindowClose() {
  return window['go']['main']['App']['WindowClose']();
}

export function WindowMinSize() {
  return window['go']['main']['App']['WindowMinSize']();
}

export function WindowToggleMaxSize() {
  return window['go']['main']['App']['WindowToggleMaxSize']();
}
