// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckLocalFiles() {
  return window['go']['main']['App']['CheckLocalFiles']();
}

export function ExportData(arg1, arg2) {
  return window['go']['main']['App']['ExportData'](arg1, arg2);
}

export function GetCharacterData(arg1) {
  return window['go']['main']['App']['GetCharacterData'](arg1);
}

export function GetWeaponData(arg1) {
  return window['go']['main']['App']['GetWeaponData'](arg1);
}

export function LoadGachaTokens() {
  return window['go']['main']['App']['LoadGachaTokens']();
}

export function LoadLocalGachaHistory(arg1, arg2) {
  return window['go']['main']['App']['LoadLocalGachaHistory'](arg1, arg2);
}

export function LoginAndFetchPlayers(arg1) {
  return window['go']['main']['App']['LoginAndFetchPlayers'](arg1);
}

export function OpenDataFolder() {
  return window['go']['main']['App']['OpenDataFolder']();
}

export function OpenOfficialLoginWindow() {
  return window['go']['main']['App']['OpenOfficialLoginWindow']();
}

export function ReloadFrontend() {
  return window['go']['main']['App']['ReloadFrontend']();
}

export function SyncDataByChoice(arg1, arg2, arg3) {
  return window['go']['main']['App']['SyncDataByChoice'](arg1, arg2, arg3);
}

export function WindowClose() {
  return window['go']['main']['App']['WindowClose']();
}

export function WindowMinSize() {
  return window['go']['main']['App']['WindowMinSize']();
}

export function WindowToggleMaxSize() {
  return window['go']['main']['App']['WindowToggleMaxSize']();
}
