// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {utils} from '../models';

export function CheckLocalFiles():Promise<main.LocalFileStatus>;

export function GetCharacterData(arg1:string):Promise<Array<utils.EndFieldCharInfo>>;

export function GetWeaponData(arg1:string):Promise<Array<utils.EndFieldWeaponInfo>>;

export function LoadGachaTokens():Promise<utils.ServerTokens>;

export function LoadLocalGachaHistory(arg1:string):Promise<main.LocalDataResponse>;

export function OpenDataFolder():Promise<void>;

export function ReloadFrontend():Promise<void>;

export function WindowClose():Promise<void>;

export function WindowMinSize():Promise<void>;

export function WindowToggleMaxSize():Promise<boolean>;
